apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    //buildToolsVersion "27.0.1"
    namespace "com.sm.maps.applib"

    defaultConfig {
        minSdkVersion 29
        targetSdkVersion 33
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }



    buildFeatures {
        aidl true
    }

    sourceSets {
        main {
            aidl.srcDirs = ['src/main/aidl']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

}

dependencies {
    //implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'com.android.support:appcompat-v7:22.2.1'
    implementation files('libs/libGoogleAnalytics.jar')
}
