apply plugin: 'com.android.application'

android {
    compileSdkVersion 34
    //buildToolsVersion "34.0.0"
    namespace "com.sm.maps"

    defaultConfig {
        applicationId "com.sm.maps"
        minSdkVersion 26
        targetSdkVersion 33
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_17
            targetCompatibility JavaVersion.VERSION_17
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

//    sourceSets {
//        main {
//            aidl.srcDirs = ['src/main/aidl']
//        }
//    }
}

dependencies {
    implementation project(':mainActivity')
    implementation 'com.android.support:appcompat-v7:22.2.1'
   // implementation 'androidx.appcompat:appcompat:1.6.1'
}
